import type { Alumnus } from '@/lib/schemas'

/**
 * Migrated from the legacy /126-2 (Alumni) page. `featured: true` promotes a
 * person onto the homepage strip -- keep that to around nine so the grid stays
 * whole rows. Blank fields are blanks in the source data, not oversights.
 */
export const alumni: Alumnus[] = [
  {
    name: 'Henry Misas',
    major: 'Mechanical Engineering',
    classYear: 2010,
    teamRole: 'President',
    currentRole: 'Program Manager',
    currentOrg: 'Tesla',
    featured: true,
  },
  {
    name: 'Jonathan Biagiotti',
    major: 'Electrical Engineering',
    classYear: 2011,
    teamRole: 'President',
    currentRole: 'Product Development Manager',
    currentOrg: 'Augury',
    featured: false,
  },
  {
    name: 'Yusuf Chauhan',
    major: 'Biomedical Engineering',
    classYear: 2012,
    teamRole: 'President',
    currentRole: 'Graduate Research Fellow',
    currentOrg: 'Houston Medical Hospital',
    featured: false,
  },
  {
    name: 'Cameron Musco',
    major: 'CS & Applied Math',
    classYear: 2012,
    currentRole: 'Assistant Professor of CS',
    currentOrg: 'UMass Amherst',
    featured: true,
  },
  {
    name: 'Christopher Musco',
    major: 'CS & Applied Math',
    classYear: 2012,
    currentRole: 'Assistant Professor of CS',
    currentOrg: 'NYU',
    featured: true,
  },
  {
    name: 'Hari Vasudevan',
    major: 'Mechanical Engineering',
    classYear: 2014,
    teamRole: 'Electrical Lead',
    currentRole: 'Sensing Systems Engineer',
    currentOrg: 'Apple',
    featured: true,
  },
  {
    name: 'Jan Kolmas',
    major: 'Mechanical Engineering',
    classYear: 2014,
    currentRole: 'Spacecraft Operations Engineer',
    currentOrg: 'European Space Agency',
    featured: true,
  },
  {
    name: 'Joseph Belter',
    major: 'Mechanical Engineering',
    classYear: 2015,
    teamRole: 'Chief Race Engineer',
    currentRole: 'Engineer',
    currentOrg: 'ClearMotion',
    featured: true,
  },
  {
    name: 'Chinmay Jaju',
    major: 'Mechanical Engineering',
    classYear: 2015,
    teamRole: 'Chief Engineer',
    currentRole: 'Business Development',
    currentOrg: 'Uber Freight',
    featured: false,
  },
  {
    name: 'Shivang Patel',
    major: 'Electrical Engineering',
    classYear: 2015,
    teamRole: 'Electrical Lead',
    currentRole: 'Student',
    currentOrg: 'Harvard Law School',
    featured: false,
  },
  {
    name: 'Alex Villarreal',
    major: 'Electrical Engineering',
    classYear: 2015,
    currentRole: 'Software Engineer',
    currentOrg: 'Google',
    featured: true,
  },
  {
    name: 'Philip Piper',
    major: 'MechE, EECS',
    classYear: 2015,
    teamRole: 'Chief Engineer',
    currentRole: 'Aerospace Engineer',
    currentOrg: 'Air Force Research Laboratory',
    featured: true,
  },
  {
    name: 'Connor Durkin',
    major: 'Electrical Engineering',
    classYear: 2016,
    currentRole: 'Trading Analyst',
    currentOrg: 'Bank of America Merrill Lynch',
    featured: false,
  },
  {
    name: 'Alex Carillo',
    major: 'EECS',
    classYear: 2016,
    currentRole: 'Software Engineer',
    currentOrg: 'SpaceX',
    featured: false,
  },
  {
    name: 'Taha Ramazanoglu',
    major: 'Mechanical Engineering',
    classYear: 2017,
    teamRole: 'President',
    currentRole: 'Mechanical Engineer',
    currentOrg: 'ClearMotion',
    featured: false,
  },
  {
    name: 'Miles Petterson',
    major: 'Mechanical Engineering',
    classYear: 2019,
    teamRole: 'Chief Engineer',
    featured: false,
  },
  {
    name: 'Patrick Lawe',
    major: 'EECS',
    classYear: 2019,
    teamRole: 'President',
    currentRole: 'Software Engineer',
    currentOrg: 'Appian',
    featured: false,
  },
  {
    name: 'Zach Wright',
    major: 'Mechanical Engineering',
    classYear: 2020,
    teamRole: 'President',
    currentRole: 'Senior Associate',
    currentOrg: 'EY Parthenon',
    featured: false,
  },
  {
    name: 'Kevin Truong',
    major: 'EECS',
    classYear: 2020,
    teamRole: 'EE Team Lead',
    currentRole: 'Software Engineer',
    currentOrg: 'Epic Systems',
    featured: false,
  },
  {
    name: 'Clarence Rodgers',
    major: 'Mechanical Engineering & CS',
    classYear: 2021,
    teamRole: 'Chief Engineer',
    currentRole: 'Mechanical Engineer',
    currentOrg: 'SpaceX',
    featured: true,
  },
  {
    name: 'Vishnu Murale',
    major: 'Computer Science',
    classYear: 2021,
    teamRole: 'Project Manager',
    currentRole: 'Analyst',
    currentOrg: 'McKinsey',
    featured: false,
  },
]
